### ISSUE TITLE
Download and Extract

### ISSUE THREAD

**Issue by emreozudogru** [lanrat/czds#6]
Is it possible to add download and extract option?

**Comment by lanrat** [comment]
If you want to get the uncompressed stream you can use the [Client.DownloadZoneToWriter](https://godoc.org/github.com/lanrat/czds#Client.DownloadZoneToWriter) and pass the stream to [gzip.NewReader](https://golang.org/pkg/compress/gzip/#NewReader) using [io.Pipe](https://godoc.org/io#Pipe).

Since CZDS provides compressed files, and its trivial to extract them after downloading with a simple shell script I'm not super enthusiastic about adding the option, but I would accept a pull request that adds this to CZDS-DL behind a `-uncompress` flag. Or you can use add that logic to your own client.

**Comment by lanrat** [comment]
Closing this for reasons in the previous comment.
